# Mock Exam Simulator Configuration

# Window Settings
window:
  title: "Mock Exam Simulator"
  width: 1000
  height: 800
  background: "#ffffff"

# Exam Settings
exam:
  default_questions: 100
  default_time_limit_minutes: 60
  base_mark: 1.00

# UI Styles
styles:
  button:
    font: ["Segoe UI", 8]
    padding: 3
    active_background: "#333333"  # A slightly lighter black/gray for active state
    default_background: "#000000"  # Black for default background
    disabled_background: "#666666"  # A gray shade for disabled state
    active_foreground: "white"
    default_foreground: "white"
    disabled_foreground: "#cccccc"  # Light gray for disabled text
    borderwidth: 0
    relief: "flat"
  label:
    font: ["Segoe UI", 12]
    background: "#ffffff"
  entry:
    padding: 5
    bordercolor: "#ced4da"
    borderwidth: 1
    relief: "solid"
  radiobutton:
    font: ["Segoe UI", 12]
    background: "#ffffff"
  checkbutton:
    font: ["Segoe UI", 12]
    background: "#ffffff"
  progressbar:
    thickness: 20
    background: "#007bff"
    troughcolor: "#e9ecef"
  answered_button:
    background: "#a3e635"  # Light green for answered questions
  active_button:
    background: "#007bff"
  viewed_button:
    background: "#dc3545"
  flagged_button:
    background: "#ff9500"  # Orange for flagged questions

# Navigation Settings
navigation:
  default_visible: false
  background: "#f1f3f5"
  canvas_height: 60

# Question Bar Settings
question_bar:
  height: 135
  font_size: 14

# Option Display Settings
option_display:
  font_size: 11